
name: Test workflow

on:

  workflow_dispatch:
    inputs:
      UPLOAD_BIN_DIR:
        description: 'Upload Bin Driectory'
        required: true
        type: boolean
        default: true
      UPLOAD_IPK:
        description: 'Upload IPK'
        required: true
        type: boolean
        default: false
      UPLOAD_RELEASE:
        description: 'Upload IPK to Release'
        required: true
        type: choice
        options:
        - true
        - false
        default: 'true'

env:
  SDK_DLINK: https://downloads.openwrt.org/releases/21.02.3/targets/x86/64/openwrt-sdk-21.02.3-x86-64_gcc-8.4.0_musl.Linux-x86_64.tar.xz # 21.02.3 x86-64 SDK
  ADD_SRC: addfeedsrc.sh
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: echo BIN${{ inputs.UPLOAD_BIN_DIR }} IPK${{ inputs.UPLOAD_IPK }} REL${{ inputs.UPLOAD_RELEASE }}

    - name: Download SDK
      run: echo '2'

    - name: Add custom feeds sources
      run: echo '3'

    - name: Update feeds
      run: echo '4'

    - name: Install feeds
      run: echo '5'

    - name: Enable cCache
      run: echo '6'

    - name: Compile IPK
      id: compile
      run: |
        echo '7'
        echo "::set-output name=status::success"

    - name: Check space usage
      if: (!cancelled())
      run: df -hT

    - name: Organize files
      id: organize
      run: |
        echo '9'
        echo "::set-output name=status::success"

    - name: Upload bin directory
      if: steps.compile.outputs.status == 'success' && github.event.inputs.UPLOAD_BIN_DIR == 'true'
      run: echo '8'

    - name: Upload IPK directory
      if: github.event.inputs.UPLOAD_IPK == 'true' && steps.organize.outputs.status == 'success' && !cancelled()
      run: echo '10'

    - name: Compress releasing files
      id: compress
      if: github.event.inputs.UPLOAD_RELEASE == 'true' && !cancelled()
      run: |
        echo '11'
        echo "::set-output name=status::success"

    - name: Generate release tag
      id: tag
      if: steps.compress.outputs.status == 'success' && !cancelled()
      run: |
        echo '12'
        echo "::set-output name=status::success"

    - name: Upload IPK to release
      if: steps.tag.outputs.status == 'success' && !cancelled()
      run: echo '13'

    - name: Delete workflow runs
      run: echo '14'

    - name: Remove old Releases
      if: github.event.inputs.UPLOAD_RELEASE == 'true' && !cancelled()
      run: echo '15'
