
name: Test workflow

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      UPLOAD_BIN_DIR:
        description: 'Upload Bin Directory'
        type: boolean
        default: true
      UPLOAD_IPK_DIR:
        description: 'Upload IPK Directory'
        type: boolean
        default: true
      UPLOAD_RELEASE:
        description: 'Upload IPKs.zip to Release'
        type: boolean
        default: true

env:
  SDK_DLINK: https://downloads.openwrt.org/releases/21.02.3/targets/x86/64/openwrt-sdk-21.02.3-x86-64_gcc-8.4.0_musl.Linux-x86_64.tar.xz # 21.02.3 x86-64 SDK
  ADD_SRC: addfeedsrc.sh
  UPLOAD_BIN_DIR: false
  UPLOAD_IPK_DIR: false
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        echo inputBIN ${{ inputs.UPLOAD_BIN_DIR }} inputIPK ${{ inputs.UPLOAD_IPK_DIR }} inputREL ${{ inputs.UPLOAD_RELEASE }}
        [ -e ${{ github.event.inputs.UPLOAD_BIN_DIR }} ] && echo "UPLOAD_BIN_DIR=${{ github.event.inputs.UPLOAD_BIN_DIR }}" >> $GITHUB_ENV

    - name: Download SDK
      run: echo '2'

    - name: Add custom feeds sources
      run: echo '3'

    - name: Update feeds
      run: echo '4'

    - name: Install feeds
      run: echo '5'

    - name: Enable cCache
      run: echo '6'

    - name: Compile IPK
      id: compile
      run: |
        echo '7'
        echo "::set-output name=status::success"

    - name: Check space usage
      if: (!cancelled())
      run: df -hT

    - name: Organize files
      id: organize
      run: |
        echo '9'
        echo "::set-output name=status::success"

    - name: Upload bin directory
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true'
      run: echo '8'

    - name: Upload IPK directory
      if: env.UPLOAD_IPK_DIR == 'true' && steps.organize.outputs.status == 'success' && !cancelled()
      run: echo '10'

    - name: Compress releasing files
      id: compress
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      run: |
        echo '11'
        echo "::set-output name=status::success"

    - name: Generate release tag
      id: tag
      if: steps.compress.outputs.status == 'success' && !cancelled()
      run: |
        echo '12'
        echo "::set-output name=status::success"

    - name: Upload IPK to release
      if: steps.tag.outputs.status == 'success' && !cancelled()
      run: echo '13'

    - name: Delete workflow runs
      run: echo '14'

    - name: Remove old Releases
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      run: echo '15'
